// export const Dataproduct = [
//     {
//         img: "img/fee9ebce-b414-7500-7c2f-0018fa33211e.jpg",
//         price: "145000",
//         type: "ao nam",
//         name: "WRINKLE FREE 11",
//         id: "1",
//         export: "VN",
//         material: " Modal Poly ",
//         feature: " Chống co rút,Thấm hút và thoát mồ hôi tổt",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//     },
//     {
//         img: "img/b649e39b-559b-0100-f228-00172c1dc894.jpg",
//         price: "146000",
//         type: "ao nam",
//         name: "WRINKLE FREE 12",
//         export: "vn",
//         material: " Modal Poly ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Chống co rút,Thấm hút và thoát mồ hôi tổt",
//         id: "2",
//     },
//     {
//         img: "img/1dc2700c-adf6-1200-cfc4-00195ca29425.jpg",
//         price: "252000",
//         type: "ao nam",
//         name: "WRINKLE FREE 10",
//         export: "vn",
//         material: " Modal Poly ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Chống co rút,Thấm hút và thoát mồ hôi tổt",
//         id: "3",
//     },
//     {
//         img: "img/e6aaff54-c571-4900-0acd-001acdb36152.jpg",
//         price: "336000",
//         type: "ao nam",
//         name: "Seventy Seven 42",
//         type1: "ao thun",
//         export: "vn",
//         material: "  Cotton 4 Chiều ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Chống co rút,Thấm hút và thoát mồ hôi tổt,Co giãn 4 chiều",
//         id: "4",
//     },
//     {
//         img: "img/28705152-e1f5-5d00-04d3-001acdb3bf29.jpg",
//         price: "262000",
//         type: "ao nam",
//         name: "Seventy Seven 01",
//         type1: "ao thun",
//         material: "  Cotton 4 Chiều ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Chống co rút,Thấm hút và thoát mồ hôi tổt,Co giãn 4 chiều",
//         id: "5",
//     },
//     {
//         img: "img/f724f7cd-3b01-2000-f6dd-001ab956ad25.jpg",
//         price: "756000",
//         type: "ao nam",
//         name: "PREMIUM 42",
//         material: "  Cotton Compact 2C ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " thoát mồ hôi tổt,Co giãn 4 chiều,Kiểm soát mùi,Điều hòa nhiệt",
//         type1: "ao polo",
//         id: "6",
//     },
//     {
//         img: "img/0d06f148-8a6b-5600-a8dc-001aa1c9bf3e.jpg",
//         price: "661000",
//         type: "ao nam",
//         name: "PREMIUM 42",
//         material: "  Cotton Compact 2C ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " thoát mồ hôi tổt,Co giãn 4 chiều,Kiểm soát mùi,Điều hòa nhiệt",
//         type1: "ao polo",
//         id: "7",
//     },
//     {
//         img: "img/609e326c-bdbe-2100-f96c-001aa1c668f0.jpg",
//         price: "436000",
//         type: "ao nam",
//         name: "PREMIUM 51",
//         material: "  Cotton Compact 2C ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " thoát mồ hôi tổt,Co giãn 4 chiều,Kiểm soát mùi,Điều hòa nhiệt",
//         type1: "ao polo",
//         id: "8",
//     },
//     {
//         img: "img/70543929-d71f-1900-9675-0018ce262f23.jpg",
//         price: "446000",
//         type: "quan nam",
//         name: "Cosmo 67",
//         export: "vn",
//         material: "   Vải Dù ",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Họa tiết nhãn ép phản quang + thêu kim tuyến",
//         id: "9",
//     },
//     {
//         img: "img/a2d6d66e-517d-a000-1121-001a791ac2e8.jpg",
//         price: "776000",
//         name: "Cosmo 56",
//         type: "quan nam",
//         export: "vn",
//         material: "   100% Polyester ",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Tỏa nhiệt bề mặt",
//         id: "10",
//     },
//     {
//         img: "img/e192778e-e2b3-2701-4fb9-001a8647ae68.jpg",
//         price: "186000",
//         type: "quan nam",
//         name: "Cosmo 38",
//         export: "vn",
//         material: "   Kaki Cotton Spandex ",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Thân trước 2 túi hộp nhỏ có nắp đậy được may đắp lên 2 túi đắp có kích thước lớn",
//         id: "11",
//     },
//     {
//         img: "img/5359c90d-d2cb-2401-7ab2-0019c0402fe4.jpg",
//         price: "312000",
//         type: "quan nam",
//         name: "PREMIUM 17",
//         export: "vn",
//         material: " Jean Cotton",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Mang đến sự thoải mái ở phần hông và đùi nhưng vẫn rất gọn gàng",
//         id: "12",
//     },
//     {
//         img: "img/0daa8bba-4348-d901-d698-001a6e182a06.jpg",
//         price: "332000",
//         type: "quan nam",
//         name: "PREMIUM 39",
//         export: "vn",
//         material: " Jean Cotton",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Mang đến sự thoải mái ở phần hông và đùi nhưng vẫn rất gọn gàng",
//         id: "13",
//     },
//     {
//         img: "img/baf807fc-38e8-2200-e1cf-001a2338dcfe.jpg",
//         price: "232000",
//         type: "quan nam",
//         name: " Cool Touch 15",
//         export: "vn",
//         material: "  COTTON DOUBLE FACE",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: "  Thoáng Khí,Nhanh khô,Độ bền cao",
//         id: "14",
//     },
//     {
//         img: "img/dbadfc7f-af0a-3500-2b91-0019258575ed.jpg",
//         price: "882000",
//         type: "quan nam",
//         name: " Cool Touch 09",
//         export: "vn",
//         material: "  COTTON DOUBLE FACE",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: "  Thoáng Khí,Nhanh khô,Độ bền cao",
//         id: "15",
//     },
//     // {
//     //     img: "img/134d83ec-13e8-1300-9212-001ab94f9f5d.jpg",
//     //     price: "239000",
//     //     type: "quan nam",
//     //     name: " Cool Touch 03",
//     //     export: "vn",
//     //     material: "  COTTON DOUBLE FACE",
//     //     intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//     //     feature: "  Thoáng Khí,Nhanh khô,Độ bền cao",
//     //     id: "16",
//     // },
//     {
//         img: "img/9fa7d31d-8f17-0200-bbc3-001994fd2703.jpg",
//         price: "32000",
//         type: "phu kien",
//         name: "PKTT Vớ Nguyên Bản V23 ",
//         export: "vn",
//         material: "  Cotton Spandex Rubber",
//         intro: "Thiết kế  rất đẹp và phong cách. Thông thoáng. Khử mùi",
//         feature: "Kỹ Thuật: kiểu dệt mắc lưới",
//         id: "17",
//     },
//     {
//         img: "img/71939105-8563-bd00-d82f-001a7b45dac6.jpg",
//         price: "552000",
//         type: "phu kien",
//         name: "PKTT Ví Da Thịnh Vượng 9",
//         export: "vn",
//         material: " Da bò nhập khẩu cao cấp dập vân",
//         intro: "Thiết kế  bóp  rất đẹp và phong cách. ",
//         feature: " Mỗi sản phẩm ví YaMe đều có hộp kraf đựng riêng cứng cáp, có nắp đậy sang trọng.",
//         id: "18",
//     },
//     {
//         img: "img/c436d731-7f51-6000-5cc4-001aa765b43c.jpg",
//         price: "512000",
//         type: "phu kien",
//         name: "PKTT Ví Da Thịnh Vượng 4",
//         export: "vn",
//         material: " Da bò tự nhiên Italy - Da Ý Marlin",
//         intro: "Thiết kế  bóp  rất đẹp và phong cách.",
//         feature: " Mỗi sản phẩm ví YaMe đều có hộp kraf đựng riêng cứng cáp, có nắp đậy sang trọng.",
//         id: "19",
//     },
//     {
//         img: "img/3bb768e1-be38-e600-5ac5-001a7b471339.jpg",
//         price: "482000",
//         type: "phu kien",
//         name: "PKTT Ví Da Thịnh Vượng 7",
//         export: "vn",
//         material: " Da bò tự nhiên Italy - Da Ý Marlin",
//         intro: "Thiết kế  bóp  rất đẹp và phong cách. ",
//         feature: " Mỗi sản phẩm ví YaMe đều có hộp kraf đựng riêng cứng cáp, có nắp đậy sang trọng.",
//         id: "20",
//     },
//     {
//         img: "img/fba12dbd-c09c-7000-9d52-001a6aca3e06.jpg",
//         price: "663000",
//         type: "phu kien",
//         name: "PKTT Ví Da Tài Lộc 03",
//         export: "vn",
//         material: " DA BÒ THẬT 100%",
//         intro: "Thiết kế  bóp  rất đẹp và phong cách. ",
//         feature: " Mỗi sản phẩm ví YaMe đều có hộp kraf đựng riêng cứng cáp, có nắp đậy sang trọng.",
//         id: "21",
//     },
//     {
//         img: "img/1a4ac6bf-9952-0100-4f28-001abcaf53b1.jpg",
//         price: "383000",
//         type: "phu kien",
//         name: "PKTT Bình Giữ Nhiệt M2",
//         export: "vn",
//         material: "  Inox 304",
//         intro: "Thiết kế  rất đẹp và phong cách.2 lớp inox cách nhiệt ",
//         feature: " Thể tích: 500ml.Giữ nhiệt 6-10 giờ",
//         id: "22",
//     },
//     {
//         img: "img/b4c019e1-bee9-0100-5010-001aa9a02ad3.jpg",
//         price: "993000",
//         type: "phu kien",
//         name: "Dây Nịt Da No Style 52",
//         export: "vn",
//         material: " DA BÒ THẬT 100%",
//         intro: "Thiết kế  rất đẹp và phong cách. ",
//         feature: " Đặc biệt: không gỉ sét.Bề mặt sáng bóng và đẹp",
//         id: "23",
//     },
//     {
//         img: "img/54943469-3e6f-e500-2ac0-001a8645a454.jpg",
//         price: "783000",
//         type: "phu kien",
//         name: " SPEED 48",
//         export: "vn",
//         material: " Kaki",
//         intro: "Thiết kế  rất đẹp và phong cách. ",
//         feature: " Kỹ thuật: Thêu 2D",
//         id: "24",
//     },

//     // {
//     //     img: "img/23d5aa4a-f2ed-6700-3121-001ab241ea7a.jpg",
//     //     price: "450000",
//     //     type: "bo sieu tap1",
//     //     name: " Miền Gió Cát 03",
//     //     export: "VN",
//     //     material: "  Kaki Contton Spandex ",
//     //     intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//     //     feature: " Áo wash có hiệu ứng nhăn tại vị trí đường may,Túi áo may dạng túi đắp phần đáy túi nhọn",
//     //     id: "28",
//     // },
//     {
//         img: "img/db2a4d50-bca7-c300-2346-001ab2493586.jpg",
//         price: "140000",
//         type: "bo sieu tap1",
//         name: " Miền Gió Cát 02",
//         export: "VN",
//         material: "  Kaki Contton Spandex ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Áo wash có hiệu ứng nhăn tại vị trí đường may,Túi áo may dạng túi đắp phần đáy túi nhọn",
//         id: "29",
//     },
//     {
//         img: "img/6e49a021-c3db-7300-9437-001ab242e2c9.jpg",
//         price: "120000",
//         type: "bo sieu tap1",
//         name: " Miền Gió Cát 16",
//         export: "VN",
//         material: "  Kaki Contton Spandex ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Áo wash có hiệu ứng nhăn tại vị trí đường may,Túi áo may dạng túi đắp phần đáy túi nhọn",
//         id: "30",
//     },
//     {
//         //  QUAN
//         img: "img/QUANCAT1.jpg",
//         price: "630000",
//         type: "bo sieu tap1",
//         export: "VN",
//         material: "  Kaki Contton Spandex ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " có hiệu ứng nhăn tại vị trí đường may,",
//         name: "Miền Gió Cát 01",
//         id: "31",
//     },
//     {
//         // QUAN
//         img: "img/f5.jpg",
//         price: "629000",
//         type: "bo sieu tap2",
//         name: "BST Thiết Kế SPEED 40",
//         export: "VN",
//         material: "900DPU Đen + 600D PU in chuyển nhiệt Xám Đậm ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Thêu đắp giống Logo Racing,",
//         name: "BST Thiết Kế SPEED 16",
//         type1: "ao thun",
//         id: "32",
//     },
//     {
//         img: "img/f6.jpg",
//         price: "630000",
//         type: "bo sieu tap2",
//         export: "VN",
//         material: "900DPU Đen + 600D PU in chuyển nhiệt Xám Đậm ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Thêu đắp giống Logo Racing,",
//         name: "BST Thiết Kế SPEED 16",
//         type1: "ao thun",
//         id: "33",
//     },
//     {
//         img: "img/f1.jpg",
//         price: "529000",
//         type: "bo sieu tap2",
//         export: "VN",
//         material: "900DPU Đen + 600D PU in chuyển nhiệt Xám Đậm ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Thêu đắp giống Logo Racing,",
//         name: "BST Thiết Kế SPEED 05",
//         id: "34",
//     },
//     {
//         img: "img/f2.jpg",
//         price: "456000",
//         type: "bo sieu tap2",
//         export: "VN",
//         material: "900DPU Đen + 600D PU in chuyển nhiệt Xám Đậm ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Thêu đắp giống Logo Racing,",
//         name: "BST Thiết Kế SPEED 44",
//         id: "35",
//     },
//     {
//         img: "img/f3.jpg",
//         price: "754000",
//         type: "bo sieu tap2",
//         name: " BST Thiết Kế SPEED 08",
//         material: "900DPU Đen + 600D PU in chuyển nhiệt Xám Đậm ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Thêu đắp giống Logo Racing,",
//         type1: "ao thun",
//         id: "36",
//     },
//     {
//         img: "img/f4.jpg",
//         price: "629000",
//         type: "bo sieu tap2",
//         name: "BST Thiết Kế SPEED 33",
//         export: "VN",
//         material: "900DPU Đen + 600D PU in chuyển nhiệt Xám Đậm ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Thêu đắp giống Logo Racing,",
//         type1: "ao thun",
//         id: "37",
//     },
//     {
//         img: "img/f7.jpg",
//         price: "778000",
//         type: "bo sieu tap2",
//         export: "VN",
//         name: "BST Thiết Kế SPEED 23",
//         material: "Vải Dù Nhăn ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: In dẻo + rã phối + dây viền",
//         id: "38",
//     },
//     {
//         img: "img/f8.jpg",
//         price: "361000",
//         type: "bo sieu tap2",
//         name: "BST Thiết Kế SPEED 93",
//         export: "VN",
//         material: "Kaki Cotton Polyeste ",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: In cao thành",
//         type1: "ao thun",
//         id: "39",
//     },
//     {
//         // quan
//         img: "img/8604e4db-be0e-0300-3189-001ab4a49c8e.jpg",
//         price: "460000",
//         type: "bo sieu tap1",
//         name: " Miền Gió Cát 16",
//         type1: "quan short",
//         id: "40",
//     },
//     {
//         img: "img/2a7ef161-b54a-3900-e8b0-001ad114117a.jpg",
//         price: "360000",
//         type: "new",
//         name: "ÁO THUN CO DÃN 4 CHIỀU",
//         export: "VN",
//         material: " Cotton 4 Chiều",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật:  In Cao",
//         id: "41",
//     },
//     {
//         img: "img/ca8dab0d-77ab-4500-34a7-001ad114d2dc.jpg",
//         price: "360000",
//         type: "new",
//         name: "ÁO THUN CO DÃN 4 CHIỀU",
//         export: "VN",
//         material: " Cotton 4 Chiều",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật:  In Cao",
//         id: "42",
//     },
//     {
//         img: "img/9e6b68df-548b-4100-3b44-001ad1149d0a.jpg",
//         price: "360000",
//         type: "new",
//         name: "ÁO THUN CO DÃN 4 CHIỀU",
//         export: "VN",
//         material: " Cotton 4 Chiều",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật:  In Cao",
//         id: "43",
//     },
//     {
//         img: "img/46544750-f16f-4a00-50ac-001ad114f266.jpg",
//         price: "360000",
//         type: "new",
//         name: "ÁO THUN CO DÃN 4 CHIỀU",
//         export: "VN",
//         material: " Cotton 4 Chiều",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật:  In Cao",
//         id: "44",
//     },
//     {
//         img: "img/32386c35-e2c2-3d00-face-001ad1143b93.jpg",
//         price: "360000",
//         type: "new",
//         name: "ÁO THUN CO DÃN 4 CHIỀU",
//         export: "VN",
//         material: " Cotton 4 Chiều",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật:  In Cao",
//         id: "45",
//     },
//     {
//         img: "img/92396938-2ef7-3500-2621-001ad113d714.jpg",
//         price: "360000",
//         type: "new",
//         name: "ÁO THUN CO DÃN 4 CHIỀU",
//         export: "VN",
//         material: " Cotton 4 Chiều",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật:  In Cao",
//         id: "46",
//     },
//     {
//         img: "img/14290bbb-799d-2a00-b46d-001ad1129712.jpg",
//         price: "360000",
//         type: "new",
//         name: "ÁO THUN CO DÃN 4 CHIỀU",
//         export: "VN",
//         material: " Cotton 4 Chiều",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật:  In Cao",
//         id: "47",
//     },
//     // {
//     //     img: "img/b4811c81-dea1-3100-2ac5-001ad113618b.jpg",
//     //     price: "360000",
//     //     type: "new",
//     //     name: "ÁO THUN CO DÃN 4 CHIỀU",
//     //     export: "VN",
//     //     material: " Cotton 4 Chiều",
//     //     intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//     //     feature: " Kỹ thuật:  In Cao",
//     //     id: "48",
//     // },

//     {
//         img: "img/vo1.jpg",
//         price: "45000",
//         type: "phu kien full",
//         name: "VỚ NGẮN S300",
//         export: "vn",
//         material: "  Cotton Spandex Rubber",
//         intro: "Thiết kế  rất đẹp và phong cách. Thông thoáng. Khử mùi",
//         feature: "Kỹ Thuật: kiểu dệt mắc lưới",
//         id: "57",
//     },
//     {
//         img: "img/vo2.jpg",
//         price: "55000",
//         type: "phu kien full",
//         name: "VỚ NGẮN S350",
//         export: "vn",
//         material: "  Cotton Spandex Rubber",
//         intro: "Thiết kế  rất đẹp và phong cách. Thông thoáng. Khử mùi",
//         feature: "Kỹ Thuật: kiểu dệt mắc lưới",
//         id: "58",
//     },
//     {
//         img: "img/vo3.jpg",
//         price: "45000",
//         type: "phu kien full",
//         name: "VỚ CỔ CAO X100",
//         export: "vn",
//         material: "  Cotton Spandex Rubber",
//         intro: "Thiết kế  rất đẹp và phong cách. Thông thoáng. Khử mùi",
//         feature: "Kỹ Thuật: kiểu dệt mắc lưới",
//         id: "59",
//     },
//     {
//         img: "img/vo4.jpg",
//         price: "45000",
//         type: "phu kien full",
//         name: "VỚ CỔ CAO L200",
//         export: "vn",
//         material: "  Cotton Spandex Rubber",
//         intro: "Thiết kế  rất đẹp và phong cách. Thông thoáng. Khử mùi",
//         feature: "Kỹ Thuật: kiểu dệt mắc lưới",
//         id: "60",
//     },
//     {
//         img: "img/non3.jpg",
//         price: "456000",
//         type: "phu kien full",
//         export: "vn",
//         material: "  Kaki",
//         intro: "Thiết kế  rất đẹp và phong cách.",
//         feature: "Họa tiết thêu 2D",
//         name: "Nón Ver6",
//         id: "61",
//     },
//     {
//         img: "img/NON7.jpg",
//         price: "796000",
//         type: "phu kien full",
//         name: "Nón Ver45",
//         export: "vn",
//         material: "Kaki ",
//         intro: "Thiết kế rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Họa tiết thêu 2D",
//         id: "62",
//     },
//     {
//         img: "img/non8.jpg",
//         price: "896000",
//         type: "phu kien full",
//         export: "vn",
//         material: "Kaki ",
//         intro: "Thiết kế  rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Họa tiết thêu 2D",
//         name: "Nón TNT8",
//         id: "63",
//     },
//     {
//         img: "img/NON10.jpg",
//         price: "846000",
//         type: "phu kien full",
//         export: "vn",
//         material: "Kaki ",
//         intro: "Thiết kế  rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Họa tiết thêu 2D",
//         name: "Nón Y2010",
//         id: "64",
//     },
//     // {
//     //     img: "img/SALE1.jpg",
//     //     price: "763000",
//     //     type: "SALE",
//     //     name: "ÁO HOODIE L8",
//     //     export: "VN",
//     //     material: " French Terry",
//     //     intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//     //     feature: " Kỹ thuật: Thấm hút thoát ẩm,Co giãn đàn hồi",
//     //     id: "65",
//     // },
//     {
//         img: "img/SALE2.jpg",
//         price: "453000",
//         type: "SALE",
//         name: "ÁO KHOÁC ALI",
//         export: "VN",
//         material: "  100% Polyester",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Bo thun cổ tay,Gấu áo có dây rút",
//         id: "66",
//     },
//     {
//         img: "img/SALE3.jpg",
//         price: "363000",
//         type: "SALE",
//         name: "ÁO HOODIE Đ8",
//         export: "VN",
//         material: " French Terry",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Thấm hút thoát ẩm,Co giãn đàn hồi",
//         id: "67",
//     },
//     {
//         img: "img/SALE4.jpg",
//         price: "520000",
//         type: "SALE",
//         name: "ÁO HOODIE J9",
//         export: "VN",
//         material: " French Terry",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Thấm hút thoát ẩm,Co giãn đàn hồi",
//         id: "68",
//     },
//     {
//         img: "img/SALE5.jpg",
//         price: "250000",
//         type: "SALE",
//         name: "ÁO KHOÁC CHỐNG NẮNG Y10",
//         export: "VN",
//         material: " vải dù",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Reverse Coil Zipper Những chiếc khoá túi này có bề mặt ngoài dẹp, phẳng trong khi răng khoá thì ở trong",
//         id: "69",
//     },
//     {
//         img: "img/SALE6.jpg",
//         price: "743000",
//         type: "SALE",
//         name: "ÁO KHOÁC API",
//         export: "VN",
//         material: " vải dù",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Reverse Coil Zipper Những chiếc khoá túi này có bề mặt ngoài dẹp, phẳng trong khi răng khoá thì ở trong",
//         id: "70",
//     },
//     {
//         img: "img/SALE7.jpg",
//         price: "753000",
//         type: "SALE",
//         name: "ÁO KHOÁC CHỐNG NẮNG Z5",
//         export: "VN",
//         material: " vải dù",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Reverse Coil Zipper Những chiếc khoá túi này có bề mặt ngoài dẹp, phẳng trong khi răng khoá thì ở trong",
//         id: "71",
//     },
//     {
//         img: "img/SALE8.jpg",
//         price: "460000",
//         type: "SALE",
//         name: "ÁO KHOÁC KL",
//         export: "VN",
//         material: "  Vải Kaki nhung gân",
//         intro: "Thiết kế của áo cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đại. Màu sắc của áo cũng rất tươi sáng và bền, không bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật:  Cổ áo, cổ tay, lai áo được bo vải gân",
//         id: "72",
//     },
//     {
//         img: "img/sale11.jpg",
//         price: "660000",
//         type: "SALE",
//         name: "QUẦN  Cosmo 28",
//         export: "VN",
//         material: "  Cotton",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Kỹ thuật: Cạp thắt lưng sử dụng cùng loại vải với quần để tạo vẻ ngoài gọn gàng, đẹp mắt",
//         id: "73",
//     },
//     {
//         img: "img/sale12.jpg",
//         price: "640000",
//         type: "SALE",
//         name: "QUẦN   B47",
//         export: "vn",
//         material: " Jean Cotton",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Mang đến sự thoải mái ở phần hông và đùi nhưng vẫn rất gọn gàng",
//         id: "74",
//     },
//     {
//         img: "img/sale13.jpg",
//         price: "350000",
//         type: "SALE",
//         name: "QUẦN SHORT F78",
//         export: "vn",
//         material: "   Vải Dù ",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Họa tiết nhãn ép  + thêu kim tuyến",
//         id: "75",
//     },
//     {
//         img: "img/sale14.jpg",
//         price: "350000",
//         type: "SALE",
//         name: "QUẦN SHORT POT13",
//         export: "vn",
//         material: "   Vải Dù ",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Họa tiết nhãn ép  kim tuyến",
//         id: "76",
//     },
//     {
//         img: "img/sale15.jpg",
//         price: "450000",
//         type: "SALE",
//         name: "QUẦN JEAN P63",
//         export: "vn",
//         material: " Jean Cotton",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Mang đến sự thoải mái ở phần hông và đùi nhưng vẫn rất gọn gàng",
//         id: "77",
//     },
//     {
//         img: "img/sale16.jpg",
//         price: "740000",
//         type: "SALE",
//         name: "QUẦN  Horus Ver1",
//         export: "vn",
//         material: " Jean Cotton",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Mang đến sự thoải mái ở phần hông và đùi nhưng vẫn rất gọn gàng",
//         id: "78",
//     },
//     {
//         img: "img/sale17.jpg",
//         price: "850000",
//         type: "SALE",
//         name: "QUẦN  Ve41",
//         export: "vn",
//         material: "  COTTON DOUBLE FACE",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: "  Thoáng Khí,Nhanh khô,Độ bền cao",
//         id: "79",
//     },
//     // {
//     //     img: "img/sale18.jpg",
//     //     price: "850000",
//     //     type: "SALE",
//     //     name: "QUẦN SHORT LI45",
//     //     export: "vn",
//     //     material: "   100% Polyester ",
//     //     intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//     //     feature: " Tỏa nhiệt bề mặt",
//     //     id: "80",
//     // },
//     {
//         img: "img/PHUKIEN1.jpg",
//         price: "250000",
//         type: "SALE",
//         name: "NÓN YI CÁ TÍNH",
//         export: "vn",
//         material: "Kaki ",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: " Họa tiết thêu 2D",
//         id: "81",
//     },
//     {
//         img: "img/PHUKIEN2.jpg",
//         price: "900000",
//         type: "SALE",
//         name: "NÓN SPEED ",
//         export: "vn",
//         material: " 100% Cotton",
//         intro: "Thiết kế của quần cũng rất đẹp và phong cách. Nó có một kiểu dáng đơn giản nhưng vẫn rất trẻ trung và hiện đạikhông bị phai màu sau một thời gian sử dụng.",
//         feature: "Kỹ thuật: Thêu 2D",
//         id: "82",
//     },
//     {
//         img: "img/PHUKIEN3.jpg",
//         price: "945000",
//         type: "SALE",
//         name: "DÂY NỊT Y10",
//         export: "vn",
//         material: " Da bò  Ý Marlin",
//         intro: "Thiết kế   rất đẹp và phong cách. ",
//         feature: "  Đặc biệt: không gỉ sét.Bề mặt sáng bóng và đẹp",
//         id: "83",
//     },
//     {
//         img: "img/PHUKIEN4.jpg",
//         price: "787000",
//         type: "SALE",
//         name: "DÂY NỊT HE45",
//         export: "vn",
//         material: " Da bò  100%",
//         intro: "Thiết kế rất đẹp và phong cách. ",
//         feature: " Đặc biệt: không gỉ sét.Bề mặt sáng bóng và đẹp",
//         id: "84",
//     },
//     {
//         img: "img/PHUKIEN5.jpg",
//         price: "660000",
//         type: "SALE",
//         name: "BÓP NEW13",
//         export: "vn",
//         material: " DA BÒ THẬT 100%",
//         intro: "Thiết kế  bóp  rất đẹp và phong cách. ",
//         feature: "  Mỗi sản phẩm ví YaMe đều có hộp kraf đựng riêng cứng cáp, có nắp đậy sang trọng.",
//         id: "86",
//     },
//     {
//         img: "img/PHUKIEN6.jpg",
//         price: "323000",
//         type: "SALE",
//         name: "BÓP YAME2016",
//         export: "vn",
//         material: " DA BÒ THẬT 100%",
//         intro: "Thiết kế  bóp  rất đẹp và phong cách. ",
//         feature: "  Mỗi sản phẩm ví YaMe đều có hộp kraf đựng riêng cứng cáp, có nắp đậy sang trọng.",
//         id: "87",
//     },
//     {
//         img: "img/PHUKIEN7.jpg",
//         price: "258000",
//         export: "vn",
//         material: " Nhựa ff2",
//         intro: "Thiết kế  rất đẹp và phong cách.2 lớp inox cách nhiệt ",
//         feature: " Thể tích: 500ml.Giữ nhiệt 4-6giờ",
//         type: "SALE",
//         name: "BÌNH NƯỚCFD99",
//         id: "88",
//     },
//     {
//         img: "img/PHUKIEN8.jpg",
//         price: "258000",
//         type: "SALE",
//         name: "BÌNH INOX G77",
//         export: "vn",
//         material: "Inox 304 ",
//         intro: "Thiết kế  rất đẹp và phong cách.2 lớp inox cách nhiệt ",
//         feature: " Thể tích: 500ml.Giữ nhiệt 6-10 giờ",
//         id: "89",
//     },
// ];
